services:
  db:
    image: postgres:latest
    container_name: spring-playlists
    environment:
      POSTGRES_DB: playlistdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
    ports:
      - "5000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: